# Generated by Django 3.1.5 on 2021-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210116_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='language',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory_while_ran',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='result_score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time_while_ran',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_token',
            field=models.CharField(default='6961a6f0-5a88-4115-9d3a-fc3e1cec4ab0', max_length=64),
            preserve_default=False,
        ),
    ]
