# Generated by Django 3.1.5 on 2021-01-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210124_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_accepted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
