# Generated by Django 3.1.5 on 2021-01-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20210125_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-score']},
        ),
    ]
