# Generated by Django 3.1.5 on 2021-06-07 10:25

from django.db import migrations, models

import account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210530_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='9999999999', max_length=10, validators=[account.validators.validate_contact_number]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Test', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
