# Generated by Django 3.2.4 on 2021-07-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210607_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_no',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
