# Generated by Django 3.2.4 on 2021-12-14 21:35

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_no',
            field=models.CharField(max_length=16, unique=True, validators=[account.validators.validate_admission_number]),
        ),
    ]
