# Generated by Django 3.1.4 on 2020-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201227_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_no',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
