# Generated by Django 3.1.5 on 2021-01-07 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models
import event.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=1024)),
                ('is_contest', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('problem_statement', models.TextField(max_length=2048)),
                ('input_statement', models.TextField(max_length=1024)),
                ('output_statement', models.TextField(max_length=1024)),
                ('contraints', models.TextField(max_length=1024)),
                ('example_input', models.TextField(max_length=512)),
                ('example_output', models.TextField(max_length=512)),
                ('example_explanation', models.TextField(max_length=1024)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('result_score', models.IntegerField()),
                ('time_while_ran', models.FloatField()),
                ('memory_while_ran', models.FloatField()),
                ('language', models.CharField(max_length=16)),
                ('solution', models.TextField(max_length=4096)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='submission_from',
            field=models.ManyToManyField(through='event.Submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_of_this_event', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='leaderboard',
            field=models.ManyToManyField(related_name='event_of_this_leaderboard', through='event.Leaderboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
