# Generated by Django 3.1.5 on 2021-01-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_submission_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='slug', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default='slug', max_length=8),
            preserve_default=False,
        ),
    ]
