# Generated by Django 3.1.5 on 2021-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210125_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ImageField(blank=True, upload_to='event_icons/'),
        ),
    ]
