# Generated by Django 3.2.4 on 2021-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210612_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default='The start of contest looks quite like ICPC: all problems immediately available for viewing/solving, the statements are simple and understandable. Choose the problem and begin to solve it. I think the idea to order problems by difficulty is good. The aim of the participant is to earn as much scores as possible.\n\nThe cost of the problem is initially the maximum points shown, which degrades with time. For each wrong submission to a problem, the points of problem is decrease as penalty.\n\nSolve the Problems in least possible time with minimum wrong submission to gain maximum score and climb up the leaderboard.', max_length=1024),
            preserve_default=False,
        ),
    ]
