# Generated by Django 3.2.4 on 2021-06-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-event__datetime', '-score']},
        ),
    ]
