# Generated by Django 3.2.4 on 2021-06-22 21:41

from django.db import migrations, models
import django.db.models.deletion
import event.models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_leaderboard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_input', models.FileField(upload_to=event.models.Testcase.get_input_testcase_path, validators=[event.validators.validate_text_file])),
                ('solution_output', models.FileField(upload_to=event.models.Testcase.get_output_testcase_path, validators=[event.validators.validate_text_file])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='event.problem')),
            ],
        ),
    ]
