# Generated by Django 3.2.4 on 2021-06-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='solution_input',
            new_name='tc_input',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='solution_output',
            new_name='tc_output',
        ),
    ]
