# Generated by Django 3.2.4 on 2021-06-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20210623_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_token',
        ),
    ]
