# Generated by Django 3.2.4 on 2021-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_submission_submission_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='no_of_testcases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
