# Generated by Django 3.2.4 on 2021-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_problem_no_of_testcases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Accepted', max_length=32),
            preserve_default=False,
        ),
    ]
