# Generated by Django 3.2.4 on 2021-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20210701_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avg_memory',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='avg_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='testcases_passed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
