# Generated by Django 3.2.4 on 2021-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20210705_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language_id',
            field=models.PositiveSmallIntegerField(default=54),
            preserve_default=False,
        ),
    ]
