# Generated by Django 3.2.4 on 2021-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_submission_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='slow_time_limit',
            field=models.FloatField(default=2, help_text='For slow languages like C#, Java, javaScript, Kotlin and Scala'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='slower_time_limit',
            field=models.FloatField(default=3, help_text='For slower languages like Lisp, PHP and Ruby.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='slowest_time_limit',
            field=models.FloatField(default=5, help_text='For slowest languages like Python and Python3.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='std_time_limit',
            field=models.FloatField(default=1, help_text='Standard time limit for all other languages including C/C++'),
        ),
    ]
