# Generated by Django 3.2.4 on 2021-07-08 15:52

from django.db import migrations, models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20210706_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.FileField(upload_to='event_icons/', validators=[event.validators.validate_image_file]),
        ),
    ]
