# Generated by Django 3.2.4 on 2021-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_event_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cpp_solution',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
