# Generated by Django 3.2.4 on 2021-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_problem_cpp_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tc_input_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tc_output_size',
            field=models.FloatField(default=0),
        ),
    ]
