# Generated by Django 3.1.4 on 2021-01-01 11:15

from django.db import migrations, models
import event.models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210101_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution_input',
            field=models.FileField(upload_to=event.models.Problem.get_input_testcase_path, validators=[event.validators.validate_text_file]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution_output',
            field=models.FileField(upload_to=event.models.Problem.get_output_testcase_path, validators=[event.validators.validate_text_file]),
        ),
    ]
